const product = [{
        "id": 49,
        "product_name": "Đồng hồ thông minh Huami Amazfit T-Rex",
        "product_slug": "dong-ho-thong-minh-huami-amazfit-t-rex",
        "product_quantity": "22",
        "product_category_id": 5,
        "product_price": "2309000",
        "product_sale": "0",
        "product_description": "Đồng hồ thông minh Huami Amazfit T-Rex sở hữu màn hình 1.3 Inch cùng kích thước khá là hầm hố nhưng chỉ nặng 36g. Mặt kính cường lực cùng với khả năng chống chịu tốt ở mọi môi trường khắc nghiệt. Dây đeo silicone đem lại cho người dùng cảm giác êm ái, thoải mái khi đeo trong thời gian dài.",
        "product_thumbnail": "img/xiaomi-amazfit-t-rex-1-3-org.jpg",
        "createdAt": "2021-01-10",
        "updatedAt": "2021-01-11"
    },
    {
        "id": 19,
        "product_name": "Laptop Acer Nitro AN515 55 70AX i7",
        "product_slug": "laptop-acer-nitro-an515-55-70ax-i7",
        "product_quantity": "28",
        "product_category_id": 2,
        "product_price": "28790000",
        "product_sale": "0",
        "product_description": "Với vi xử lí tân tiến, card đồ họa rời khủng cùng khả năng tản nhiệt tối ưu, laptop Acer Nitro AN515 55 70AX i7 (NH.Q7NSV.001) là một “vũ khí” lợi hại sẵn sàng cùng bạn chiến đấu mọi trận chiến căng thẳng.",
        "product_thumbnail": "img/acer-nitro-an515-55-70ax-i7-10750h-8gb-512gb-4gb-g-091920-101950-600x600.jpg",
        "createdAt": "2021-01-10",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 1,
        "product_name": "Điện thoại iPhone 12 Pro Max 512GB",
        "product_slug": "dien-thoai-iphone-12-pro-max-512gb",
        "product_quantity": "9",
        "product_category_id": 1,
        "product_price": "41990000",
        "product_sale": "0",
        "product_description": "iPhone 12 Pro Max 512GB - đẳng cấp từ tên gọi đến từng chi tiết. Ngay từ khi chỉ là tin đồn thì chiếc smartphone này đã làm đứng ngồi không yên bao “fan cứng” nhà Apple, với những nâng cấp vô cùng nổi bật hứa hẹn sẽ mang đến những trải nghiệm tốt nhất về mọi mặt mà chưa một chiếc iPhone tiền nhiệm nào có được.",
        "product_thumbnail": "img/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg",
        "createdAt": "2021-01-09",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 16,
        "product_name": "Laptop Dell Vostro 3590 i7",
        "product_slug": "laptop-dell-vostro-3590-i7",
        "product_quantity": "35",
        "product_category_id": 2,
        "product_price": "20490000",
        "product_sale": "0",
        "product_description": "Laptop Dell Vostro 3590 i7 (GRMGK2) là phiên bản laptop đồ họa kĩ thuật có thiết kế hiện đại, cấu hình khỏe với vi xử lí gen 10 và card đồ họa rời. Đây chính là chiếc laptop đáng cân nhắc đối với dân đồ họa hay sinh viên khối ngành kĩ thuật.",
        "product_thumbnail": "img/dell-vostro-3590-i7-grmgk2-220718-220718-600x600.jpg",
        "createdAt": "2021-01-10",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 18,
        "product_name": "Laptop Lenovo Gaming 15IMH05 i7",
        "product_slug": "laptop-lenovo-gaming-15imh05-i7",
        "product_quantity": "15",
        "product_category_id": 2,
        "product_price": "23490000",
        "product_sale": "0",
        "product_description": "Sở hữu cấu hình khủng bao gồm chip Intel Core i7 gen 10, RAM 8 GB cùng card đồ họa rời mạnh mẽ, Lenovo Gaming 15IMH05 i7 (81Y40068VN) hoàn toàn xứng danh là một trong những chiếc laptop chơi game mạnh hiện nay.",
        "product_thumbnail": "img/lenovo-gaming-15imh05-i7-81y40068vn-225389-600x600.jpg",
        "createdAt": "2021-01-10",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 7,
        "product_name": "Điện thoại Samsung Galaxy Note 20 Ultra 5G Trắng",
        "product_slug": "dien-thoai-samsung-galaxy-note-20-ultra-5g-trang",
        "product_quantity": "25",
        "product_category_id": 1,
        "product_price": "26990000",
        "product_sale": "0",
        "product_description": "Samsung Galaxy Note 20 Ultra 5G Trắng mẫu flagship hàng đầu của Samsung hoàn hảo về mọi mặt, từ thiết kế sang trọng đẳng cấp cho đến hiệu năng cực khủng ẩn chứa bên trong. Đặc biệt hơn cả là chiếc bút S Pen đầy “quyền năng” của dòng Note giờ đây cũng đã được nâng lên một tầm cao mới.",
        "product_thumbnail": "img/samsunggalaxynote20ultratrangnew-600x600-600x600.jpg",
        "createdAt": "2021-01-09",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 14,
        "product_name": "Laptop Apple MacBook Air M1 2020 8GB/256GB",
        "product_slug": "laptop-apple-macbook-air-m1-2020-8gb256gb",
        "product_quantity": "7",
        "product_category_id": 2,
        "product_price": "28990000",
        "product_sale": "0",
        "product_description": "Laptop Apple MacBook Air M1 2020 (MGN93SA/A) có thiết kế nhỏ gọn thuận tiện mang theo bên mình, chip M1 cho cấu hình mạnh mẽ tốc độ xử lý nhanh sẽ là trợ thủ đắc lực cho bạn trong công việc.",
        "product_thumbnail": "img/apple-macbook-air-2020-mgn93saa-1-600x600.jpg",
        "createdAt": "2021-01-10",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 13,
        "product_name": "Laptop Apple MacBook Pro M1 2020 8GB/512GB",
        "product_slug": "laptop-apple-macbook-pro-m1-2020-8gb512gb",
        "product_quantity": "1",
        "product_category_id": 2,
        "product_price": "39990000",
        "product_sale": "0",
        "product_description": "Apple Macbook Pro M1 2020 (MYD92SA/A) với hiệu năng cực kỳ mạnh mẽ tích hợp chip Apple M1 lần đầu xuất hiện trên MAC đã xuất hiện trên thị trường laptop, con laptop này hứa hẹn sẽ mang đến cho bạn một sản phẩm “Pro” chưa từng thấy.",
        "product_thumbnail": "img/apple-macbook-pro-2020-myd92saa-600x600.jpg",
        "createdAt": "2021-01-09",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 15,
        "product_name": "Laptop Asus Gaming Rog Strix G512 i7",
        "product_slug": "laptop-asus-gaming-rog-strix-g512-i7",
        "product_quantity": "28",
        "product_category_id": 2,
        "product_price": "28490000",
        "product_sale": "0",
        "product_description": "Laptop Asus Gaming Rog Strix G512 i7 (IAL001T) là chiếc laptop gaming có cấu hình mạnh mẽ và thiết kế hầm hố đậm chất gaming. Máy được trang bị chip Intel Core i7 thế hệ mới nhất cùng với màn hình cao cấp chuẩn gaming giúp bạn thỏa sức chiến những tựa game cực đỉnh.",
        "product_thumbnail": "img/asus-gaming-rog-strix-g512-i7-ial001t-272120-022128-225687-600x600.jpg",
        "createdAt": "2021-01-10",
        "updatedAt": "2021-01-10"
    },
    {
        "id": 17,
        "product_name": "Laptop Dell G5 15 5500 i7",
        "product_slug": "laptop-dell-g5-15-5500-i7",
        "product_quantity": "34",
        "product_category_id": 2,
        "product_price": "34490000",
        "product_sale": "0",
        "product_description": "Laptop Dell G5 15 5500 i7 (70228123) với cấu hình mạnh mẽ, thiết kế đẹp mắt, chiếc laptop Dell này sẽ đem lại trải nghiệm chơi game cực đã, làm việc mượt mà.",
        "product_thumbnail": "img/dell-g5-15-5500-i7-70228123-094621-024632-600x600.jpg",
        "createdAt": "2021-01-10",
        "updatedAt": "2021-01-10"
    }
]